In [1]:
import torch

In [5]:
print(x.grad)

None


In [7]:
from kymatio import Scattering1D
from torch.autograd import backward

learning_rate = 0.1
n_iterations = 100

N = 2**12
scattering = Scattering1D(J=10, shape=(N,))

# Random guess
x = torch.randn((N,), requires_grad=True)
Sx = scattering(x)

# Target
y = torch.randn((N,), requires_grad=False)#was false
Sy = scattering(y)

#with torch.no_grad():
#    x = y.clone()
x.requires_grad = True
print(x.grad)
print(torch.norm(Sx-Sy))

for it_id in range(n_iterations):
    # Backpropagation
    backward(torch.norm(Sx - Sy))
    delta_x = x.grad
    print(x.grad)

    # Gradient descent
    with torch.no_grad():
        x = x - delta_x * learning_rate
    x.requires_grad = True

    # New forward propagation
    Sx = scattering(x)

    # Measure the new loss
    print(torch.norm(Sx - Sy))

None
tensor(0.0435, grad_fn=<NormBackward0>)
tensor([-2.1096e-04, -1.4737e-04, -3.4251e-05,  ...,  2.1952e-05,
         9.6653e-05,  1.5466e-04])
tensor(0.0435, grad_fn=<NormBackward0>)
tensor([-2.1083e-04, -1.4706e-04, -3.3917e-05,  ...,  2.2224e-05,
         9.6872e-05,  1.5481e-04])
tensor(0.0435, grad_fn=<NormBackward0>)
tensor([-2.1069e-04, -1.4674e-04, -3.3585e-05,  ...,  2.2497e-05,
         9.7090e-05,  1.5495e-04])
tensor(0.0434, grad_fn=<NormBackward0>)
tensor([-2.1055e-04, -1.4643e-04, -3.3252e-05,  ...,  2.2769e-05,
         9.7308e-05,  1.5510e-04])
tensor(0.0434, grad_fn=<NormBackward0>)
tensor([-2.1041e-04, -1.4611e-04, -3.2919e-05,  ...,  2.3042e-05,
         9.7526e-05,  1.5524e-04])
tensor(0.0433, grad_fn=<NormBackward0>)
tensor([-2.1027e-04, -1.4579e-04, -3.2587e-05,  ...,  2.3314e-05,
         9.7744e-05,  1.5539e-04])
tensor(0.0433, grad_fn=<NormBackward0>)
tensor([-2.1013e-04, -1.4548e-04, -3.2255e-05,  ...,  2.3587e-05,
         9.7961e-05,  1.5553e-04])
tensor(0

tensor(0.0411, grad_fn=<NormBackward0>)
tensor([-2.0228e-04, -1.2796e-04, -1.3842e-05,  ...,  3.8871e-05,
         1.0995e-04,  1.6343e-04])
tensor(0.0411, grad_fn=<NormBackward0>)
tensor([-2.0214e-04, -1.2765e-04, -1.3517e-05,  ...,  3.9144e-05,
         1.1016e-04,  1.6357e-04])
tensor(0.0410, grad_fn=<NormBackward0>)
tensor([-2.0200e-04, -1.2734e-04, -1.3193e-05,  ...,  3.9417e-05,
         1.1037e-04,  1.6370e-04])
tensor(0.0410, grad_fn=<NormBackward0>)
tensor([-2.0186e-04, -1.2704e-04, -1.2868e-05,  ...,  3.9690e-05,
         1.1058e-04,  1.6384e-04])
tensor(0.0409, grad_fn=<NormBackward0>)
tensor([-2.0172e-04, -1.2673e-04, -1.2544e-05,  ...,  3.9963e-05,
         1.1079e-04,  1.6398e-04])
tensor(0.0409, grad_fn=<NormBackward0>)
tensor([-2.0158e-04, -1.2642e-04, -1.2220e-05,  ...,  4.0236e-05,
         1.1100e-04,  1.6412e-04])
tensor(0.0409, grad_fn=<NormBackward0>)
tensor([-2.0143e-04, -1.2611e-04, -1.1896e-05,  ...,  4.0509e-05,
         1.1121e-04,  1.6425e-04])
tensor(0.0408

In [3]:
torch.norm(Sx-Sy)

tensor(0.0380, grad_fn=<NormBackward0>)