In [1]:
import torch

In [12]:
from kymatio import Scattering1D
from torch.autograd import backward

learning_rate = 0.1
n_iterations = 100

N = 2**12
scattering = Scattering1D(J=10, shape=(N,))

# Random guess
x = torch.randn((N,), requires_grad=True)
Sx = scattering(x)

# Target
y = torch.randn((N,), requires_grad=False)#was false
Sy = scattering(y)

#with torch.no_grad():
#    x = y.clone()
x.requires_grad = True

print(torch.norm(Sx-Sy))

for it_id in range(n_iterations):
    # Backpropagation
    backward(torch.norm(Sx - Sy))
    delta_x = x.grad
    print(x.grad)

    # Gradient descent
    with torch.no_grad():
        x = x - delta_x * learning_rate
    x.requires_grad = True

    # New forward propagation
    Sx = scattering(x)

    # Measure the new loss
    print(torch.norm(Sx - Sy))

tensor(0.0349, grad_fn=<NormBackward0>)
tensor([-1.5245e-04, -4.6150e-04, -2.1622e-04,  ..., -4.4550e-05,
         1.0885e-04, -2.9372e-06])
tensor(0.0349, grad_fn=<NormBackward0>)
tensor([-1.5210e-04, -4.6086e-04, -2.1555e-04,  ..., -4.4130e-05,
         1.0939e-04, -2.6746e-06])
tensor(0.0348, grad_fn=<NormBackward0>)
tensor([-1.5175e-04, -4.6022e-04, -2.1487e-04,  ..., -4.3711e-05,
         1.0993e-04, -2.4116e-06])
tensor(0.0348, grad_fn=<NormBackward0>)
tensor([-1.5140e-04, -4.5959e-04, -2.1420e-04,  ..., -4.3292e-05,
         1.1047e-04, -2.1486e-06])
tensor(0.0347, grad_fn=<NormBackward0>)
tensor([-1.5105e-04, -4.5895e-04, -2.1352e-04,  ..., -4.2872e-05,
         1.1101e-04, -1.8864e-06])
tensor(0.0347, grad_fn=<NormBackward0>)
tensor([-1.5069e-04, -4.5831e-04, -2.1285e-04,  ..., -4.2453e-05,
         1.1155e-04, -1.6228e-06])
tensor(0.0347, grad_fn=<NormBackward0>)
tensor([-1.5034e-04, -4.5767e-04, -2.1217e-04,  ..., -4.2033e-05,
         1.1209e-04, -1.3599e-06])
tensor(0.0346

tensor(0.0327, grad_fn=<NormBackward0>)
tensor([-1.3086e-04, -4.2166e-04, -1.7522e-04,  ..., -1.9411e-05,
         1.4085e-04,  1.2906e-05])
tensor(0.0326, grad_fn=<NormBackward0>)
tensor([-1.3049e-04, -4.2097e-04, -1.7453e-04,  ..., -1.8994e-05,
         1.4138e-04,  1.3170e-05])
tensor(0.0326, grad_fn=<NormBackward0>)
tensor([-1.3012e-04, -4.2028e-04, -1.7384e-04,  ..., -1.8578e-05,
         1.4190e-04,  1.3434e-05])
tensor(0.0326, grad_fn=<NormBackward0>)
tensor([-1.2976e-04, -4.1959e-04, -1.7315e-04,  ..., -1.8163e-05,
         1.4242e-04,  1.3698e-05])
tensor(0.0325, grad_fn=<NormBackward0>)
tensor([-1.2939e-04, -4.1890e-04, -1.7246e-04,  ..., -1.7748e-05,
         1.4294e-04,  1.3962e-05])
tensor(0.0325, grad_fn=<NormBackward0>)
tensor([-1.2902e-04, -4.1821e-04, -1.7178e-04,  ..., -1.7332e-05,
         1.4346e-04,  1.4225e-05])
tensor(0.0325, grad_fn=<NormBackward0>)
tensor([-1.2865e-04, -4.1751e-04, -1.7109e-04,  ..., -1.6917e-05,
         1.4399e-04,  1.4489e-05])
tensor(0.0324

In [11]:
torch.norm(Sx-Sy)

tensor(0.0266, grad_fn=<NormBackward0>)